spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password : ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

jwt:
  secret: "SUPER-STRONG-HYPER-ULTRA-SECRET-KEY"
  expiration-millis: 3600000

