spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8085

# Docker 환경에서의 서비스 URL
services:
  lost-service:
    url: http://lost-service:8083
  found-service:
    url: http://found-service:8084
